version: '3'
services:

  redis-sentinel1:
    image: boyj-redis-sentinel
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - MASTERPORT=6379
      - CLIENTPORT=26379
      - MASTERHOST=127.0.0.1
      - CLIENTHOST=127.0.0.1
      - QUORUM=2
      - DOWN_AFTER_MILLISEC=5000
      - FAILOVER_TIMEOUT=30000

  redis-sentinel2:
    image: boyj-redis-sentinel
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - MASTERPORT=6379
      - CLIENTPORT=26380
      - MASTERHOST=127.0.0.1
      - CLIENTHOST=127.0.0.1
      - QUORUM=2
      - DOWN_AFTER_MILLISEC=5000
      - FAILOVER_TIMEOUT=30000

  redis-sentinel3:
    image: boyj-redis-sentinel
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - MASTERPORT=6379
      - CLIENTPORT=26381
      - MASTERHOST=127.0.0.1
      - CLIENTHOST=127.0.0.1
      - QUORUM=2
      - DOWN_AFTER_MILLISEC=5000
      - FAILOVER_TIMEOUT=30000
