version: '3'
services:
  coturn:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coturn
    network_mode: host
    ports:
      - "3478:3478/udp" # STUN/TURN UDP
      - "3478:3478/tcp" # STUN/TURN TCP
      - "3479:3479/udp" # STUN/TURN UDP Alt port (RFC5780 support)
      - "3479:3479/tcp" # STUN/TURN TCP Alt port (RFC5780 support)
      - "5349:5349/udp" # STUN/TURN DTLS
      - "5349:5349/tcp" # STUN/TURN TLS
      - "5350:5350/udp" # STUN/TURN DTLS Alt port (RFC5780 support)
      - "5350:5350/tcp" # STUN/TURN TLS Alt port (RFC5780 support)
      - "49152:65535/udp" # UDP media ports for TURN relay
    environment:
      PORT: 3478
      ALT_PORT: 3479
      TLS_PORT: 5349
      TLS_ALT_PORT: 5350
      MIN_PORT: 49152
      MAX_PORT: 65535
      JSON_CONFIG: '{"config":["no-auth", "cli-password=boyj", "realm=boyj", "user=boyj:boyj", "web-admin"]}'
  netdata:
    image: netdata/netdata
    restart: always
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro